import { Action, Resource, CompanyRole, ShipRole } from '@/lib/types/iam';

/**
 * Company-scope permissions (apply across entire company; admin/owner trump ship scope)
 */
export const COMPANY_POLICY: Record<CompanyRole, Partial<Record<Resource, Action[]>>> = {
  owner: {
    company_settings: ['read','update','manage_roles','invite','export'],
    ship_profile: ['read','create','update','delete','export'],
    ship_documents: ['read','create','update','delete','export'],
    crew_hr: ['read','create','update','delete','export'],
    crew_assignments: ['read','assign','update'],
    inventory: ['read','create','update','delete','export'],
    inventory_txn: ['read','create'],
    requisition: ['read','create','update','approve','export'],
    purchase_order: ['read','create','update','approve','export'],
    invoice: ['read','create','update','approve','post','export'],
    vendor: ['read','create','update','delete','export'],
    task: ['read','create','update','delete','export'],
    shift: ['read','create','update','delete','export'],
    log: ['read','create','update','delete','export'],
    job: ['read','create','update','delete','export'],
    application: ['read','update','delete','export'],
    stats: ['read','export'],
  },
  admin: {
    company_settings: ['read','update','invite','export'],
    ship_profile: ['read','create','update','delete','export'],
    ship_documents: ['read','create','update','delete','export'],
    crew_hr: ['read','create','update','delete','export'],
    crew_assignments: ['read','assign','update'],
    inventory: ['read','create','update','delete','export'],
    inventory_txn: ['read','create'],
    requisition: ['read','create','update','approve','export'],
    purchase_order: ['read','create','update','approve','export'],
    invoice: ['read','create','update','approve','post','export'],
    vendor: ['read','create','update','delete','export'],
    task: ['read','create','update','delete','export'],
    shift: ['read','create','update','delete','export'],
    log: ['read','create','update','delete','export'],
    job: ['read','create','update','delete','export'],
    application: ['read','update','delete','export'],
    stats: ['read','export'],
  },
  hr: {
    crew_hr: ['read','create','update','delete','export'],
    crew_assignments: ['read','assign','update'],
    job: ['read','create','update','delete','export'],
    application: ['read','update','delete','export'],
    ship_documents: ['read'],
    stats: ['read'],
  },
  procurement: {
    requisition: ['read','create','update','approve','export'],
    purchase_order: ['read','create','update','approve','export'],
    invoice: ['read','create','update','post','export'],
    vendor: ['read','create','update','delete','export'],
    inventory: ['read'],
    inventory_txn: ['read'],
    ship_documents: ['read'],
    stats: ['read'],
  },
  finance: {
    invoice: ['read','approve','post','export'],
    purchase_order: ['read','approve','export'],
    requisition: ['read'],
    vendor: ['read','update'],
    stats: ['read','export'],
  },
  viewer: {
    ship_profile: ['read'],
    ship_documents: ['read'],
    crew_hr: ['read'],
    inventory: ['read'],
    requisition: ['read'],
    purchase_order: ['read'],
    invoice: ['read'],
    vendor: ['read'],
    task: ['read'],
    shift: ['read'],
    log: ['read'],
    job: ['read'],
    application: ['read'],
    stats: ['read'],
  },
};

/**
 * Ship-scope permissions (apply only to specific ship where user holds the role)
 */
export const SHIP_POLICY: Record<ShipRole, Partial<Record<Resource, Action[]>>> = {
  master: {
    ship_profile: ['read','update'],
    ship_documents: ['read','create','update'],
    crew_assignments: ['read','assign','update'],
    requisition: ['read','create','update','approve'],
    task: ['read','create','update','delete'],
    shift: ['read','create','update','delete'],
    inventory: ['read'],
    inventory_txn: ['read','create'],
    log: ['read','create','update'],
    stats: ['read'],
  },
  chief_engineer: {
    ship_documents: ['read','create','update'],
    inventory: ['read','update'],
    inventory_txn: ['read','create'],
    requisition: ['read','create','update'],
    task: ['read','create','update'],
    shift: ['read','update'],
    log: ['read','create'],
    stats: ['read'],
  },
  chief_officer: {
    ship_documents: ['read','create','update'],
    requisition: ['read','create','update'],
    task: ['read','create','update'],
    shift: ['read','update'],
    log: ['read','create'],
    inventory: ['read'],
    stats: ['read'],
  },
  officer_2: {
    ship_documents: ['read','update'],
    task: ['read','create','update'],
    log: ['read','create'],
    inventory: ['read'],
    stats: ['read'],
  },
  officer_3: {
    ship_documents: ['read'],
    task: ['read','create','update'],
    log: ['read','create'],
    inventory: ['read'],
    stats: ['read'],
  },
  bosun: {
    task: ['read','update'],
    shift: ['read'],
    log: ['read','create'],
    inventory: ['read'],
  },
  ship_procurement: {
    requisition: ['read','create','update'],
    inventory: ['read'],
    inventory_txn: ['read'],
    vendor: ['read'],
    stats: ['read'],
  },
  ship_crew_manager: {
    crew_assignments: ['read','assign','update'],
    ship_documents: ['read'],
    task: ['read','create','update'],
    shift: ['read','create','update'],
    stats: ['read'],
  },
  viewer_ship: {
    ship_profile: ['read'],
    ship_documents: ['read'],
    inventory: ['read'],
    requisition: ['read'],
    task: ['read'],
    shift: ['read'],
    log: ['read'],
    stats: ['read'],
  },
};
